mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^',include('polls.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name="polls"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    #detail
    url(r'^(?P<question_id>[0-9]+)/$',views.detail,name='detail'),
    #results
    url(r'^(?P<choice_id>[0-9]+)/results/$',views.results,name='results'),
    #vote
    url(r'^(?P<choice_id>[0-9]+)/vote/$',views.vote,name='vote'),
]

polls/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
import datetime
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
    	return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
    		return self.choice_text

polls/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

#from django.shortcuts import render
from django.template import loader
# Create your views here.
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from .models import Question,Choice


def index(request):
    latest_question_list=Question.objects.order_by('-pub_date')[:5]
    template=loader.get_template('polls/index.html')
    context={'latest_question_list':latest_question_list}
    return HttpResponse(template.render(context,request))

def detail(request,question_id):
	question = get_object_or_404(Question, pk=question_id)
	return render(request, 'polls/detail.html', {'question': question})   
def results(request,choice_id):
	result = get_object_or_404(Choice, pk=choice_id)
	return render(request, 'polls/results.html', {'result': result})
def vote(request,choice_id):
	vo = get_object_or_404(Choice, pk=choice_id)
	return render(request, 'polls/vote.html', {'vo': vo})

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li><a href="{% url 'polls:results' choice.id%}">{{ choice.choice_text }} </a></li>
{% endfor %}
</ul>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ result.choice_text }}</h1>
<ul>
{% if result %}
    <li>Do you think {{ result.choice_text }} is the correct answer? <br></li>
    <a href="{% url 'polls:vote' result.id %}"><font color="red">View votes</font></a>
{% else %}
	<h1>The choice has been removed</h1>
{%endif%}
</ul>

polls/templates/polls/vote.html
<font color="red"><center><h1>{{ vo.votes }} votes </h1><center></font>